<robot name="3_dof" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="wheel_separation" value="0.68" /> 
<xacro:property name="wheel_radius" value="0.25" /> 
<xacro:property name="wheel_width"  value="0.010" />
<xacro:property name="body_height"  value="0.1" /> 
<xacro:property name="body_width"   value="0.050" /> 
<xacro:property name="body_length"  value="0.035" />

<link name="3dof_body">

    <visual>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
      <geometry>
        <mesh filename="package://krang_simplified/3dof/base2.dae" />
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0"/>
      <mass value="0.180"/>
      <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
    </inertial>
    
  </link>

  <link name="wheelR">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
      </geometry>
    </collision>

    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0.030"/>
     <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
    </inertial>

    <soft_shape>
	    <total_mass>0.04</total_mass>
	    <geometry>
	        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
	    </geometry>
		<kv>500.0</kv>
		<ke>0.0</ke>
		<damp>5.0</damp>
        </soft_shape>

  </link>

    <link name="wheelL">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
      </geometry>
    </collision>

    <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0.030"/>
     <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
    </inertial>

    <soft_shape>
	    <total_mass>0.04s</total_mass>
	    <geometry>
	        <mesh filename="package://krang_simplified/3dof/wheel.dae" />
	    </geometry>
		<kv>500.0</kv>
		<ke>0.0</ke>
		<damp>5.0</damp>
        </soft_shape>

  </link>

  <joint name="jointR" type="continuous">
    <parent link="3dof_body"/>
    <child link="wheelR"/>
    <origin xyz = "0 ${-wheel_separation * 0.5} 0" rpy="0 0 0" />
	<axis xyz="0 1 0" /> 
  </joint>

  <joint name="jointL" type="continuous">
    <parent link="3dof_body"/>
    <child link="wheelL"/>
    <origin xyz = "0 ${+wheel_separation * 0.5} 0" rpy="0 0 0" />
	<axis xyz="0 1 0" /> 
  </joint>

  <gazebo>
	<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
	<robotNamespace>/3dof</robotNamespace>
	<robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
	<legacyModeNS>true</legacyModeNS>
	</plugin>
  </gazebo>

  <gazebo>
   <plugin name="edumip_balance_ros_gazebo_plugin" filename="libedumip_balance_ros_gazebo_plugin.so">
   <rosDebugLevel>3</rosDebugLevel>
   <updateRate>100</updateRate>
   <robotBaseFrame>3dof_body</robotBaseFrame>
   <leftJoint>jointL</leftJoint>
   <rightJoint>jointR</rightJoint>
   <wheelSeparation>${wheel_separation}</wheelSeparation>
   <wheelDiameter>0.068</wheelDiameter>
   <commandTopic>/edumip/cmd</commandTopic>
   <stateTopic>/edumip/state</stateTopic> 
   </plugin>
 </gazebo>

</robot>
