<?xml version="1.0"?>
<robot name="edumip_my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Numerical Macros - units are meters and radians -->
  <xacro:property name="wheel_separation" value="0.070" /> 
  <xacro:property name="wheel_radius"     value="0.034" /> 
  <xacro:property name="wheel_width"      value="0.010" />
  <xacro:property name="body_height"      value="0.1"   /> 
  <xacro:property name="body_width"       value="0.050" /> 
  <xacro:property name="body_length"      value="0.035" /> 
  
  <link name="edumip_body">

    <visual>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="Blue">
        <color rgba="0 0.0 1.0 0.5"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.17 0"/>      
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/> 
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 -0.5" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    
  </link>


  <link name="wheelR">

    <visual>
      <origin xyz="0 0 0" rpy="1.57079 0  0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="Green">
        <color rgba="0.0 1.0 0.0 0.5"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57079 0  0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 -0.0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="1" iyz="0" izz="0.1"/>
    </inertial>

  </link>


  <link name="wheelL">

    <visual>
      <origin xyz="0 0 0" rpy="1.57079 0  0" />      
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 0.5"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57079 0  0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 -0.0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="1" iyz="0" izz="0.1"/>
    </inertial>

  </link>

  
  <joint name="jointR" type="continuous">
    <parent link="edumip_body"/>
    <child link="wheelR"/>
    <origin xyz="0 ${-wheel_separation * 0.5} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  
  <joint name="jointL" type="continuous">
    <parent link="edumip_body"/>
    <child link="wheelL"/>
    <origin xyz="0 ${+wheel_separation * 0.5} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <gazebo reference="edumip_body">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="wheelR">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="wheelL">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo>
   <plugin name="edumip_balance_ros_gazebo_plugin" filename="libedumip_balance_ros_gazebo_plugin.so">
   <rosDebugLevel>3</rosDebugLevel>
   <updateRate>100</updateRate>
   <robotBaseFrame>3dof_body</robotBaseFrame>
   <leftJoint>jointL</leftJoint>
   <rightJoint>jointR</rightJoint>
   <wheelSeparation>${wheel_separation}</wheelSeparation>
   <wheelDiameter>0.068</wheelDiameter>
   <commandTopic>/edumip/cmd</commandTopic>
   <stateTopic>/edumip/state</stateTopic> 
   </plugin>
  </gazebo>



</robot>

